spring:
  application:
    name: shake-backend
  # DataSource Config
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.142.94.41:3306/db_user
    username: root
    password: C123456lq!
  session:
    timeout: 86400
    store-type: redis
  #redis配置
  redis:
    database: 0
    port: 6379
    host: localhost
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: overend.top
        same-site: none
        secure: true
