spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: shake-backend
  rabbitmq:
    host: 43.142.94.41
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  file-storage:
    qiniu-kodo:
      - platform: qiniu-kodo-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: KHPczwJUTjCmRLdNQf18S9cm9_Rbbo3zURo_aNBe
        secret-key: ew_lCGtHPTP1pi8C1VLQnWkRDkWPOFAgBznn5737
        bucket-name: luke-permission
        domain: http://qn.overend.top/ # 访问域名，注意“/”结尾，例如：http://abc.hn-bkt.clouddn.com/
        base-path: darktalk-picture/ # 基础路径
    default-platform: qiniu-kodo-1
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 3138065252@qq.com
    password: szulkdbkdzpwdebc
    from: 3138065252@qq.com
    properties:
      mail:
        smtp:
          auth: true
          stattls:
            enable: true
            required: true
  # DataSource Config
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://43.142.94.41:3306/db_user
#    username: root
#    password: C123456lq!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_darktalk
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  #redis配置
  redis:
    database: 3
    port: 6379
    host: 192.168.56.128
    password: 123456
server:
  port: 8081
  servlet:
    context-path: /api
#    session:
#      cookie:
#        domain: 192.168.137.215
#        same-site: none
#        secure: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# MinIO 配置
minio:
  endpoint: http://192.168.56.128:9000      # MinIO服务地址
  fileHost: http://192.168.56.128:9000      # 文件地址host
  bucketName: luke-forum                      # 存储桶bucket名称
  accessKey: admin                         # 用户名
  secretKey: 12345678                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m

qiniu:
  accessKey: KHPczwJUTjCmRLdNQf18S9cm9_Rbbo3zURo_aNBe
  secretKey: ew_lCGtHPTP1pi8C1VLQnWkRDkWPOFAgBznn5737
  bucket: luke-permission
  domain: http://qn.overend.top/